name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set NODE_OPTIONS
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/oldtoncells:latest
